# Site settings
title: SiCo Docs
description: Docs and guide 
email: sinerwr@gmail.com
baseurl: 
url: "https://docs.sico.io"
favicon: /favicon.png

timezone: Asia/Shanghai
future: false

permalink: /:year/:month/:day/:title
markdown: kramdown


github_username: SiCo-Ops
github_repo: SiCo

disqus_short_name: sinerwr
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  SiCo:
    display_name: SiCo
    email: sinerwr@gmail.com
    github: SiCo-Ops
